### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by Leandro7141** [traditionalism/modified-density-deluxe#1]
Hi !

An error is in your script.

NPCs stay present even if I change the values to 0.0
![image](https://user-images.githubusercontent.com/55460457/181933305-a7f688f9-ee97-46ea-a7a1-fea14c54f5d2.png)

**Comment by traditionalism** [comment]
Hey! I apologize about that, I just pushed some changes. If you would like to re-download and test them out that would be great.

**Comment by Leandro7141** [comment]
Thanks for your changes.
I didn't want to make a script like that and yours suits me perfectly

**Comment by traditionalism** [comment]
Glad to hear it works!
